In [2]:
import numpy as np
import copy
start=np.array([[1,2,3],[0,4,6],[7,5,8]])
goal=np.array([[1,2,3],[4,5,6],[7,8,0]])
def heuristic(start,goal):
  h=0
  for i in range(len(start)):
    for j in range(len(start[i])):
      if start[i][j]!=goal[i][j]:
        h+=1
  return h
def left(s):
  c=0
  for i in range(len(s)):
    for j in range(len(s[i])):
          if(s[i][j]==0):
            try:
              s[i][j]=s[i][j-1]
              s[i][j-1]=0
              c=1
              break
            except IndexError:
                  continue
    if c==1:
        break
  return s
def right(s):
  c=0
  for i in range(len(s)):
    for j in range(len(s[i])):
          if(s[i][j]==0):
            try:
              s[i][j]=s[i][j+1]
              s[i][j+1]=0
              c=1
              break
            except IndexError:
                  continue
    if c==1:
        break
  return s
def up(s):
    c=0
    for i in range(len(s)):
        for j in range(len(s[i])):
            if(s[i][j]==0):
              try:
                s[i][j]=s[i-1][j]
                s[i-1][j]=0
                c=1
                break
              except IndexError:
                    continue
        if c==1:
            break
    return s
def down(s):
    c=0
    for i in range(len(s)):
        for j in range(len(s[i])):
            if(s[i][j]==0):
              try:
                s[i][j]=s[i+1][j]
                s[i+1][j]=0
                c=1
                break
              except IndexError:
                    continue
        if c==1:
            break
    return s

def astar(start,goal):
  while(np.allclose(start,goal)==False):
    hl=heuristic(left(copy.deepcopy(start)),goal)
    hr=heuristic(right(copy.deepcopy(start)),goal)
    hu=heuristic(up(copy.deepcopy(start)),goal)
    hd=heuristic(down(copy.deepcopy(start)),goal)
    mini=min(hl,hr,hu,hd)
    if mini==hl:
      start=left(start)
      print("left")
    elif mini==hd:
      start=down(start)
      print('d')
    elif mini==hr:
      start=right(start)
      print('r')
    else:
      start=up(start)
      print('u')
    print(start)
astar(start,goal)

r
[[1 2 3]
 [4 0 6]
 [7 5 8]]
d
[[1 2 3]
 [4 5 6]
 [7 0 8]]
r
[[1 2 3]
 [4 5 6]
 [7 8 0]]
